name:                persistent-eventsource
version:             0.3.0
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2023 Jappie Klooster"
github:              "jappeace/persistent-event-source"
synopsis:            Persistent based event sourcing.
description:         Event source library for persistent databases.
category:            Database

extra-source-files:
- Readme.md
- LICENSE
- Changelog.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities
    - -Wcpp-undef
    - -fwarn-tabs
    - -Wpartial-fields
    - -fdefer-diagnostics
    - -Wunused-packages

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5
- persistent-mtl >= 0.3.0.0 && < 0.7.0.0
- unliftio-core
- monad-logger
- persistent
- time
- esqueleto-mtl

library:
  source-dirs: src

tests:
  unit:
    main:                Test.hs
    ghc-options: -Wno-unused-packages
    source-dirs:
    - test
    dependencies:
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - persistent-eventsource
